//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dui.rc
//
#define ID_PROP                         3
#define ID_RESET                        4
#define IDD_CONTROLS                    101
#define IDS_PROJNAME                    105
#define IDD_PANEL_DIALOG                108
#define IDR_MENU_FRAME                  109
#define IDR_MENU_POP                    111
#define IDD_STRINGEDITDLG               120
#define IDD_INPUT_TEXT                  125
#define IDD_MENU_EDITDLG                145
#define IDD_POPLIST                     148
#define IDD_OLELIST                     149
#define IDR_XML1                        162
#define IDR_XML2                        163
#define IDC_BUTTON1                     202
#define IDD_DIALOG1                     202
#define IDR_ACCELERATOR1                202
#define IDD_DIALOG2                     207
#define IDC_RADIO1                      210
#define IDC_RADIO2                      211
#define IDC_BUTTON3                     215
#define IDC_RADIO5                      216
#define IDC_RADIO6                      217
#define IDC_COMBO1                      219
#define IDC_EDIT1                       220
#define IDC_ZOOMIN                      221
#define IDC_ZOOMOUT                     222
#define IDC_SYSFRAME                    223
#define IDC_SELFFRAME                   224
#define IDC_PROGRESS1                   236
#define IDC_TAB1                        237
#define IDC_EDIT2                       238
#define IDC_TAB2                        239
#define IDC_TREE1                       240
#define IDC_ANIMATE1                    242
#define IDC_EDIT_OBJECT                 1004
#define IDC_EDIT_INPUT                  1004
#define IDC_EDIT_LANGUAGE               1004
#define IDC_STRING_VALUE                1004
#define IDC_TREE_MENU                   1017
#define IDC_LIST1                       1030
#define IDC_LIST2                       1035
#define IDC_CHECK1                      1038
#define IDC_SCROLLBAR1                  1042
#define IDC_SPIN1                       1043
#define IDC_SLIDER1                     1044
#define IDC_PROGRESS2                   1045
#define IDM_FRAME_SAVE                  40001
#define IDM_FRAME_OPEN                  40002
#define IDM_SHOW_PROPERTY               40006
#define IDM_SHOW_CONTROLS               40007
#define IDM_ITEM_DELETE                 40008
#define IDM_DIALOG_PROPERTY             40009
#define IDM_TOOL_TEST                   40016
#define IDM_CONTROL_DELETE              40017
#define IDM_CONTROL_ALIGN_LEFT          40018
#define IDM_CONTROL_ALIGN_TOP           40019
#define IDM_CONTROL_ALIGN_RIGHT         40021
#define IDM_CONTROL_ALIGN_BOTTOM        40022
#define IDM_MOVE_UP                     40024
#define IDM_MOVE_DOWN                   40025
#define IDM_FRAME_SAVEAS                40026
#define IDM_SHOW_HIDE                   40027
#define IDM_ADD_NEWLANGUAGE             40029
#define IDM_FRAME_LOADLANG              40032
#define IDM_FRAME_SAVELANG              40033
#define IDM_ZOOMIN                      40034
#define IDM_ZOOMOUT                     40035
#define IDM_BACK                        40036
#define IDM_FORWARD                     40037
#define IDM_FRAME_SAVESKIN              40038
#define IDM_CHECKUNDLG                  40039
#define IDM_CHECKUNMARCO                40040
#define IDM_TEST_LANGUAGE               40041
#define IDM_RESETCONTROLID              40042
#define IDM_RESET_MARTIX                40044
#define IDM_TOOL_ADDFILE                40046
#define IDM_TOOL_DELFILE                40047
#define IDM_SETUSER                     40049
#define IDM_MERGE                       40050
#define ID_REDO                         40052
#define IDM_IMPORT_DLG_WIN              40054
#define IDM_IMPORT_DLG_DLL              40055
#define IDM_ABOUT                       40056
#define IDM_SAVE_DFT_XML                40057
#define IDM_SEE_SYS_COLOR               40059
#define IDM_CHECKKEYWORD                40060
#define IDM_FRAME_SAVESEL               40061
#define IDM_BLOCKNEXT                   40062
#define IDM_TRACKFOCUS                  40063
#define IDM_KEEPPOPWIN                  40064
#define IDM_RECORDWIN                   40065
#define IDM_TRACK_FOCUS_WIN             40066
#define IDM_TRACK_CAPTURE_WIN           40067
#define IDM_TRACK_FG_WIN                40068
#define IDM_TRACK_IME                   40069
#define IDM_TRACK_ACC                   40070
#define IDM_VIEW_ANIMATEWINDOW          40071
#define IDM_P_EMBED_WGT                 40072
#define IDM_WGT_EMBED_P                 40073
#define IDM_STRESS_TESTING              40075
#define IDM_HELP                        40076
#define IDM_UI_LIGHT                    40077
#define IDM_UI_DARK                     40078
#define IDM_UI_HIGHCONTRAST             40079
#define IDM_HELPCP                      40081
#define IDM_HELPCTRLS                   40082
#define IDM_RECORDFLIP                  40083
#define IDM_DISABLEGHOST                40084
#define IDM_DEL_HWND                    40085
#define IDM_DISABLEASSERT               40086
#define IDM_TEST_LOADPROXY              40095
#define IDM_TRANSLATE                   40097
#define IDM_GPU_MEMORY                  40099
#define IDM_PARSE_PDB                   40101
#define IDM_RECORDMSG                   40102
#define IDM_BLOCK_INJECT                40103
#define IDM_ITEM_DETACH                 40104
#define IDM_SPY_MSG_OBJ                 40105
#define IDM_ITEM_DETACH_EVER            40107
#define IDM_GPU_LOST                    40108
#define IDM_ITEM_DETACH_ALL             40109
#define IDM_MEM_ANALYSIS                40110
#define IDM_DLL_ANALYSIS                40111
#define IDM_ENABLE_MEM_ANALYSIS         40112
#define IDM_VIEW_DRAWXXX                40113
#define IDM_BLOCK_EVENT                 40114
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_EDIT_FIND_PREVIOUS           0xE12D

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         40115
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
