
static const char gl_VS[] = 
    "#version 140\r\n"
    "\r\n"
    "\r\n"
    "\r\n"
    "uniform type_CBuffer\r\n"
    "{\r\n"
    "    mat4 proj;\r\n"
    "} CBuffer;\r\n"
    "\r\n"
    "in vec2 in_var_POSITION0;\r\n"
    "in vec4 in_var_COLOR0;\r\n"
    "in vec2 in_var_TEXCOORD0;\r\n"
    "out vec4 varying_COLOR0;\r\n"
    "out vec2 varying_TEXCOORD;\r\n"
    "\r\n"
    "void main()\r\n"
    "{\r\n"
    "    gl_Position = CBuffer.proj * vec4(in_var_POSITION0, 1.0, 1.0);\r\n"
    "    varying_COLOR0 = in_var_COLOR0;\r\n"
    "    varying_TEXCOORD = in_var_TEXCOORD0;\r\n"
    "}\r\n"
    "\r\n"
    "";